---
title: "Tidyverse Recap"
author: "Bizovi Mihai"
---

## Warm-up toy example

The dataset is about sleep patterns in different mammal species.

$$
y \sim N(\mu, \sigma) 
$$


```{r load-packages}
#| echo: true
#| output: false
#| warning: false

library(tidyverse) # Hadley Wickham
library(tidyr)
```

```{r why-use-pipes}
#| warning: false

msleep %>% 
  tail(10) %>% 
  mutate(sleep_total_min = sleep_total * 60) %>% 
  glimpse()

you_better_not <- glimpse(
  mutate(
    head(msleep),
    sleep_total_min = sleep_total * 60
  )
)
```

```{r categ-cardinality}
#| warning: false

msleep %>% 
  select_if(is.character) %>% 
  tidyr::gather() %>% 
  group_by(key, value) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  filter(key == "vore")
```


```{r selecting-columns}
#| warning: false

# Args: takes as an input the column name
# Returns true or false
keep_columns <- function(col) {
  is.numeric(col) || is.character(col) # implicit return
}

avg_vore_sleep <- ggplot2::msleep %>% 
  dplyr::select(
    name, 
    genus:conservation, 
    awake, 
    starts_with("sleep_"), # for regex match("o.+er")
    ends_with("wt")
  ) %>%
  mutate(total_hours = sleep_total + awake) %>% 
  filter(total_hours == 24.0) %>% 
  select(-total_hours) %>%  # can also use one_of(c("genus", "order"))
  select_if(keep_columns) %>%
  select_if(~(is.numeric(.) & mean(., na.rm = TRUE) > 10) | is.character(.)) %>% 
  group_by(vore) %>%
  summarise(
    average_sleep = mean(sleep_total, na.rm = TRUE), 
    lb_sleep = mean(sleep_total, na.rm = TRUE) - 1.6*sd(sleep_total, na.rm = TRUE),
    ub_sleep = mean(sleep_total, na.rm = TRUE) + 1.6*sd(sleep_total, na.rm = TRUE)
  ) 

avg_vore_sleep %>% 
  ggplot(aes(x = vore, y = average_sleep)) +
  geom_col() + 
  geom_errorbar(aes(ymin = lb_sleep, ymax = ub_sleep), width = .2) +
  theme_minimal() + 
  labs(x = "What does that mammal eat?", y = "Average Sleep Time")
```

```{r}
msleep %>% 
  filter(!is.na(sleep_total)) %>% 
  ggplot(aes(x=sleep_total, color = vore)) + 
  stat_ecdf(geom = "step") + 
  theme_minimal()
```


