---
title: "Introduction to Dimensionality Reduction"
output: html_document
---

```{r load-packages}
library(tidyverse)
library(FactoMineR)
library(factoextra)
```

```{r}
df_wine <- read.csv("data/data_PCA_ExpertWine.csv", sep=";", dec = ".")
head(df_wine)
```

```{r}
pca_results <- FactoMineR::PCA(
  df_wine,             # the original dataframe
  scale.unit = TRUE,   # communicate that the package scales the data
  quali.sup = 1:2,     # additional qualitative data for exploration
  quanti.sup = 30:31,  # additional quantitative data for plotting
  graph = FALSE
)
```

```{r}
```


```{r}
# factoextra::fviz_pca_ind(pca_results)
factoextra::fviz_pca_var(
  pca_results, 
  repel = TRUE, 
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
  col.var = "contrib",
  alpha.var = "cos2",
)
```


```{r}
factoextra::fviz_pca_ind(
  pca_results, col.ind = df_wine$Label, 
  palette = c("#00AFBB", "#E7B800", "#FC4E07"),
  addEllipses = FALSE
)
```
```{r}
fviz_eig(pca_results)
```

```{r}
fviz_pca_contrib(pca_results, "var")
```



```{r}
df_wine[c(2, 10), ]
```

```{r}
data(diabetes, package = "mclust")
diabetes %>% head()
```

```{r}
pca_results_diabetes <- FactoMineR::PCA(
  diabetes,             # the original dataframe
  scale.unit = TRUE,   # communicate that the package scales the data
  quali.sup  = 1,      # additional qualitative data for exploration
  graph      = FALSE
)
```

```{r}
fviz_eig(pca_results_diabetes)
```
```{r}
factoextra::fviz_pca_biplot(
  pca_results_diabetes, col.ind = diabetes$class, 
  palette = c("#00AFBB", "#E7B800", "#FC4E07"),
  addEllipses = TRUE, 
  geom.ind = "point",
  alpha = "cos2"
)
```
```{r}
summary(pca_results_diabetes)
```





