---
title: "MLR3 Pipelines"
output: html_document
---

```{r import-packages}
library(tidyverse)
library(mlr3)
library(mlr3pipelines)
library(mlr3verse)
library(data.table)
# library(xgboost)

set.seed(12345)
```

```{r}
tsk_credit <- tsk("german_credit")
tsk_credit$data() %>% head()
tsk_credit$data()$credit_risk %>% table()
```
```{r}
tsk_credit$missings() / tsk_credit$nrow
```

```{r}
test_encoder <- po("encode", method = "one-hot")
test_encoder$train(list(tsk_credit))
```

```{r}
lrn_xgboost <- lrn("classif.xgboost", nrounds = 50, predict_type = "prob")
```

```{r}
graph <- po("encode") %>>% 
  po("scale") %>>%
  lrn_xgboost

plot(graph)
```
```{r}
graph_lrn <- as_learner(graph)
resampling <- rsmp("cv", folds = 5)
resampling_res <- resample(task = tsk_credit, learner = graph_lrn, resampling = resampling)
```
```{r}
resampling_res$score()
```
```{r}
as.data.table(graph_lrn$param_set)[, .(id, class, lower, upper, nlevels)]
```
```{r}
graph_lrn$param_set$values$encode.method = to_tune(c("one-hot", "treatment"))

instance <- tune(
  method = "grid_search", 
  task = tsk_credit,
  learner = graph_lrn,
  resampling = rsmp("cv", folds = 5),
  measure = msr("classif.ce")
)
```

```{r}
as.data.table(mlr_pipeops)
```





