project:
  type: website

website:
  title: "Decision Science Course"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: "Pragmatic Data Science"
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    left:
      - href: 01_fundamentals/0_study_guide.qmd
        text: "| 1. Business |"
      - href: 01_fundamentals/prob_study_guide.qmd
        text: "| 2. Stats |"
      - href: references.qmd
        text: "| 3. Bayes |"
    right: 
      - href: about_me.qmd
        text: "About Me"
      - icon: bi-journal-bookmark
        href: https://mihaibizovi.com/
        text: "Blog"
      - icon: github
        href: https://github.com/bizovi/decision-making
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/

  sidebar:
    # - id: fundamentals
    title: "Decision-Making for the brave and true"
    style: "docked"
    background: light
    collapse-level: 1

    contents: 
      - href: index.qmd
        text: "i. Introduction"
      - href: philosophy.qmd
        text: "ii. Course philosophy"
      - text: "iii. On scientific process"
        href: sci_process.qmd
      - text: "iv. Why study all of that?"
        href: 01_fundamentals/prerequisites.qmd
      - text: "-----"
      - section: "1. Business School and Methodology"
        href: 01_fundamentals/0_study_guide.qmd
        contents:
        - href: 01_fundamentals/0_study_guide.qmd
          text: "Syllabus & Study Guide"
        - href: 01_fundamentals/roadmap.qmd
          text: "Schedule & Roadmap"
        - href: 01_fundamentals/1_applications.qmd
          text: "1. Application Domains & Use-Cases"
        - href: 01_fundamentals/2_performance_strategy.qmd
          text: "2. Performance and Strategy"
        - href: 01_fundamentals/background.qmd
          text: "3. What is AI and Cybernetics?"
        - href: 01_fundamentals/4_ml_stats.qmd
          text: "4. Analytics, ML, Stats"
        - href: 01_fundamentals/learning.qmd
          text: "5. Learning from Data: Intuition and Bias"
      - text: "-----"
      - section: "2. Fundamentals of Probability & Statistics"
        href: 01_fundamentals/prob_study_guide.qmd
        contents:
        - href: 01_fundamentals/prob_study_guide.qmd
          text: "Syllabus & Study Guide"
        - href: roadmap_prob.qmd
          text: "Schedule & Roadmap"
      - text: "-----"
      - section: "3. Applied Bayesian Statistics"
        href: references.qmd
        contents:
        - href: references.qmd
          text: "Syllabus & Study Guide"
        - href: roadmap_bayes.qmd
          text: "Schedule & Roadmap"
      - text: "-----"
      - section: "~ Simulation of economic processes"
        href: sim/1_intro.qmd
        contents:
        - href: sim/1_intro.qmd
          text: "1. Introduction"
        - href: sim/1L_bday_problem.qmd
          text: "1L. Birthday problem"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "2. The Probability Triple"
        - href: sim/2L_safari.qmd
          text: "2L. Safari trips"
        - href: sim/3_lln.qmd
          text: "3. Three core theorems"
        - href: sim/3L_CLT.qmd
          text: "3L. Most dangerous equation"

  page-navigation: true
  page-footer:
    left: "The course I wish I had. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: yeti # simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    toc: true
    
editor: source
reference-location: margin
  
comments:
  hypothesis: 
    theme: clean

resources:
  - CNAME