project:
  type: website

website:
  title: "Modern Decision Science"
  favicon: img/favicon.jpeg
  open-graph:
    locale: es_ES
    site-name: "Pragmatic Data Science"
  google-analytics: "G-TNKQREJHQW"

  navbar:
    search: true
    right: 
      - href: about_me.qmd
        text: "About Me"
      - icon: bi-journal-bookmark
        href: https://mihaibizovi.com/
        text: "Blog"
      - icon: github
        href: https://github.com/bizovi/decision-making-website
      - icon: linkedin
        href: https://www.linkedin.com/in/mihai-bizovi-56982abb/

  sidebar:
    # - id: fundamentals
    title: "Decision-Making for the brave and true"
    style: "docked"
    background: light
    collapse-level: 1

    contents: 
      - section: "Introduction and Background"
        href: index.qmd
        contents:
        - href: index.qmd
          text: "i. Why decision science?"
        - href: philosophy.qmd
          text: "ii. Course philosophy"
        - text: "iii. Business context"
          href: business_context.qmd
        - text: "iv. On scientific process"
          href: sci_process.qmd
        # - text: "v. AI, ML, Cybernetics"
        #   href: 01_fundamentals/ai_ml_cybernetics.qmd
      - text: "-----"
      - section: "Study guides"
        contents:
        - href: 01_fundamentals/prob_study_guide.qmd
          text: "1. Probability and Statistics Study Guide"
        - href: references.qmd
          text: "2. Bayesian Statistics Study Guide"
      - text: "-----"
      - section: "Simulation of economic processes"
        href: sim/1_intro.qmd
        contents:
        - href: sim/1_intro.qmd
          text: "1. Introduction"
        - href: sim/1L_bday_problem.qmd
          text: "1L. Birthday problem"
        - href: 01_fundamentals/stat_foundations.qmd
          text: "2. The Probability Triple"
        - href: sim/2L_safari.qmd
          text: "2L. Safari trips"
        - href: sim/3_lln.qmd
          text: "3. Three core theorems"
        - href: sim/3L_CLT.qmd
          text: "3L. Most dangerous equation"
      - text: "-----"
      - section: "Appendix"
        contents:
        - text: "1. Why study all of that?"
          href: 01_fundamentals/prerequisites.qmd

  page-navigation: true
  page-footer:
    left: "The course I wish I had. Built with ❤️ by Mihai Bizovi"

bibliography: references.bib
highlight-style: pygments

format:
  html:
    theme: 
      light: yeti # simplex
      dark: cyborg
    page-layout: full
    css: styles.css
    toc-location: left
    toc: true
    
editor: source
reference-location: margin
  
comments:
  hypothesis: 
    theme: clean

resources:
  - CNAME