---
author:
  - name: Mihai Bizovi
    id: mb
    degrees: 
    - "VP of Decision Science"

format:
  html:
    toc-location: left

title: "Module III: Applied Bayesian Statistics"
---


After the first two modules, we should have a solid foundation for building more realistic models. As discussed in the introduction, randomized experiments and A/B tests have obvious limitations: might be unfeasible, unethical, or just not the right tool. Even when we design experiments or surveys, we still need to model non-response, correct for biases, and account for confounds -- meaning, engage in modeling.

::: {.column-margin}

In my opinion, among many excellent resources, Richard McElreath's 2023 lectures on statistical rethinking is the best way to learn the kind of modeling which fits our course and problem space. 

:::

I think that the best way to study regression and generalized linear models is to think very carefully about the causal processes underlying the phenomenon we're studying. The big advantage of switching to a Bayesian perspective and GLMs, is that we treat all models under an unified framework. This means, we can focus on science and much less on the mathematical intricacies of advanced econometrics.


::: {.column-page-inset-right}

|   | Lecture Agenda      | Keywords  | Case Studies / Activities |
|---|------------------|----------------------------------|---------------------------|
| 1 | Introduction to Bayesian Statistics | Estimating proportions with Beta-Binomial, counts with Gamma-Poisson, defining priors | Elections, Football Goals, Speed of Light |
| 2 | Regression and the Bayesian Workflow | DAGs of influence, categorical variables, assumptions, nonlinearities, splines, simulation | E2E example on Howell's study on height and weight. Summarizing estimands |
| 3 | Confounds. Good and Bad controls | Deep-dive on translating DAGs into statistical models. Adjustment set, backdoor criterion | E2E example of Waffle houses and divorce rates. Spurious correlations |
| ~ | Overfitting and Validation | Prior and posterior checks, LOO-CV, LOO-PIT, regularization, robust regression, simulation-based calibration | TBD |
| 4 | Multiple Groups and Hierarchical Models | Complete pooling, No pooling, Partial pooling. Post-stratification and non-representative samples | Radon concentration, Starbucks wait times, Customer LTV, Elections polls |
| 5 | Binomial GLMs | Link functions, Simpson's paradox | 1973 Berkeley admissions|
| 6 | Poisson GLMs | Overdispersion, zero-inflated, Negative Binomial | Campus Crime, Student absence |
| 7 | Hierarchical GLMs | Deep-dive into model formulation. Studies on stage anxiety and plumonary fibrosis. | Basketball Fouls, AirBnb reviews, Seat Belts |
| 8 | Longitudinal Data | Challenges of multilevel time series | Teenage drinking, sleep study |
| ~ | Special topics | BART and Gaussian Processes  | TBD  |
| ~ | Special topics | Missing data and measurement error | TBD |



