---
format:
  html:
    toc-location: left
slide-format: revealjs
---

# Business School: Study Guide

In the study guide we go into more details and granularity -- with references, readings, and practices for particular topics within each lecture. Keep in mind the [course philosophy](../philosophy.qmd), which will help you in how to approach the study of a complicated subject and refer to ["Why did you study all of that?"](prerequisites.qmd) if I invoke a certain prerequisite and you feel rusty.

::: {.column-margin}

Some lectures are conceptual and you might go into more depth by reading. Some are highly technical and you want to go through the math and practice/code on suggested case-studies.
:::


<!-- ## How to navigate a lecture

You might've noticed that every lecture starts with a brief motivation, and then will have this kind of flowchart of arguments and ideas. It is supposed to be your guide and a roadmap, so that you don't get lost in various detours taken and keep the big picture in mind.  -->

<!-- My recommendation is that you go back to this diagram at the end of the reading or lecture, try to remember individual arguments and think for yourself how are they related, what is the golden thread connecting them. [^thread]

[^thread]: This is a course in which we look at the widest possible range of methods and models, without going into excruciating detail, as I don't know which ones will be useful for your particular applications and problems. The idea is to find the optimal tool for the job.  -->


```{mermaid}
%%| label: fig-mermaid
%%| fig-width: 9
%%| fig-cap: |
%%|   A mind map of lectures grouped by theme so you can navigate the study guide easier. See below all the topics, case-studies, references, and readings for each chapter or lecture.

flowchart TD

    DM[Decision Science] -- big picture --> App[Domains & Use-Cases]
     --> Strat[Business Strategy] --> Adv[Analytics vs ML vs Stats]

    DM -- bussiness econ --> NW[Newsvendor] --> PD[Pricing Decisions] 
        --> Churn[Churn & LTV]

    DM -- methodology --> ML[Learning & Bias] --> ML12[12 Steps of ML] 
        --> Stat[12 Steps of Stats]


    style NW fill:#f7f5bc
    style PD fill:#f7f5bc
    style Churn fill:#f7f5bc
```

<!-- We start with real-world applications of data science, define what AI, Cybernetics, Big Data, Analytics, Machine Learning mean. Then, we figure out why did we study all those mathy and computer science subjects during the Bachelor's degree. Next, we discuss what can go wrong while drawing conclusions from data -- culminating in a discussion of a problem of choice you're passionate about. -->

## Introduction and Course Philosophy

First, make sure you read the [introduction](../index.qmd#module-1-business-school-for-data-scientists) for a motivation and brief summary of what are we going to study, then review the [schedule and syllabus](roadmap.qmd#module-i-business-school-for-data-scientists) in order to understand how the course can be structured in particular lectures. 

- Understand the particularities of decision-making in the business environment
- Why I prefer "decision science" over "data science"
- Necessary admin stuff and [project requirements](../index.qmd#full-stack-data-apps). Think about your goals, aspirations, interests and hobbies, so that you can pick a fun use-case
- For a survey of applications and **use-cases in various domains**, [read here](1_applications.qmd).



```{=html}
<iframe class="slide-deck" src="slides/lecture1" width="100%" height="500"></iframe>
```



## Decisions and Strategy in Business Context

I build upon the previous lecture to develop the story of decisions in a business environment. We need additional terminology, concepts, and models in order to structure the problem space. What is key here, is to get immersed and **put yourself in the shoes** of decision-makers. Read the [second chapter](2_performance_strategy.qmd).

- Evolution of firm's performance in time. Why, Where, How? [^strat-dyn]
    - Status quo, desired, and feared trajectories. 
    - Tradeoffs and limited resources, SWOT Analysis
- What is strategy? What makes good or bad strategy? [^perils-strat]
- Business Analyst's Workflow
- What is a Value Chain? Data Science Strategy Safari [^strat-safari]
- Overview of **open datasets**, especially for BI & Analytics

[^strat-dyn]: Read Kim Warren's article on "The Dynamics of Strategy" [here](https://strategydynamics.com/free/assets/The%20Dynamics%20of%20Strategy,%202016.pdf)

[^perils-strat]: Read the article published in McKinsey by Richard Rumelt ["The perils of bad strategy"](https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/the-perils-of-bad-strategy)

[^strat-safari]: Read about the framework of aligning business objectives to data science use-cases. Data Science Strategy Safari at [bayesianquest](https://bayesianquest.com/2018/11/13/data-science-strategy-safari-aligning-data-science-strategy-to-org-strategy/)

::: {.callout-note}
## Case-Study: LRB Subscriptions

Take a subscription-based publication like [London Review of Books](https://www.lrb.co.uk/), and analyze it using the tools and frameworks you learned in the course. Think about acquisition, churn, printing, transportation, and market share. How can it grow? What would make it profitable?
:::


::: {.callout-note}
## Case-Study: Food Stamps and Fermi Estimation

There is a good reason why management consultants practice Fermi Estimation (sanity, order-of-magnitude checks) and it is asked in many interviews. Take a look at the case study on [Food Stamp Fraud](https://callingbullshit.org/case_studies/case_study_foodstamp_fraud.html) by Carl Bergstrom and Jevin West in Calling Bullshit.
:::

```{=html}
<iframe class="slide-deck" src="slides/lecture2" width="100%" height="500"></iframe>
```




## Decision-Making Under Uncertainty at Scale

In the previous lecture we learned how to better structure business problems and now it's time to bridge it with the subject matter of this course. Read the [third chapter](4_ml_stats.qmd).

- Clarify what I mean by AI and Cybernetics and the historical confusion [^jordan]
- When do we need Analytics vs Statistics vs Machine Learning?
- A note on interdisciplinarity and thinking in buckets
- Agents and Environments. Sources of Uncertainty 


[^jordan]: K. Pretz, "[Stop Calling Everything AI](https://spectrum-ieee-org.cdn.ampproject.org/c/s/spectrum.ieee.org/amp/stop-calling-everything-ai-machinelearning-pioneer-says-2652904044), Machine-Learning Pioneer Says"; M. Jordan, "[Artificial  Intelligence](https://hdsr.mitpress.mit.edu/pub/wot7mkc1/release/9) - The Revolution Hasn’t Happened Yet"

::: {.callout-note}
## Case-Study: DTC Fashion E-Commerces

Choose a direct-to-consumer e-commerce, like Zara, H&M, or a marketplace like Zalando (the big players in the oligopoly). How does a potential business strategy look like? What are some use-cases for Data Science / AI which can improve their outcomes?
:::

::: {.callout-note}
## Case-Study: Uber and Dynamic Pricing

In the case of Uber, Bolt (ride sharing platforms), we're very much interested in same questions as before, however, we need to get a grasp on the idea of market-making. If you were to reverse-engineer the pricing algorithms, how would you go about doing it?

:::



## Newsvendor Problem and Demand Planning

Demand planning, especially demand forecasting and inventory optimization is an obvious and widespread application of the models and methods from the course. The newsvendor problem is a good way to get started in this area of businesses.

In the economics' courses you might've solved this problem analytically, under strong assumptions, but we have a huge problem of trying to quantify and take into account the uncertainty. Therefore, we rely on simulation, motivate the need for statistical inference and optimization algorithms. [^newsvendor]

[^newsvendor]: There is an excellent presentation of the newsvendor problem by Adam Fleischhacker in [Chapter 3](https://www.persuasivepython.com/2-decisionanalysis) and [Chapter 5](https://www.persuasivepython.com/4-multidimarrays) of "Persuasive Python". [Chapter 20](https://www.causact.com/intro#intro) of his Business Analytics book contains another classic economic problem interpreted in modern way. If you prefer, there is a [video lecture](https://www.youtube.com/watch?v=QLsSPnwWS_M) on the newsvendor.

::: {.callout-note}
## Case-Study: TIME INC. printing

In the paper ["Newsvendors Tackle the Newsvendor Problem"](https://www.jstor.org/stable/20141257), Koschat, Berk et. al. show how an analysis and optimization of printing decisions led to TIME INC. to revise its policies and generate additional $\$3.5m$ in profit.
:::

::: {.callout-note}
## Case-Study: Restaurant Data and Project Ideas 

Besides Persuasive Python, you can find an alternative case-study on ["Yaz" restaurant data](https://opimwue.github.io/ddop/tutorial_modules/tutorial.html), which makes playing around with the newsvendor problem easy, due to its Python package. 
:::

For an academic paper with a meta-analysis of data-driven approaches to the newswendor problem, check out [S. Buttler, A. Philippi](https://ml-eval.github.io/assets/pdf/ICLR22_Workshop_ML_Eval_DDNV.pdf).


## Learning, Intuition, and Bias. What is ML? 

At this point you will have a better grasp of the business environment, the processes involved in decision-making and had exposure to multiple contexts via case-studies. The newsvendor problem exposed the fact that we need additional skills and understanding of statistical modeling, machine learning and analytics. Read [chapter five](learning.qmd).

I start the introduction to machine learning in an unorthodox way, from a **cognitive science perspective**. The reason is: because we gain additional insights into decision-making. But don't worry, top courses like Shai Ben-David's "Understanding Machine Learning" [^lrn-data] and Yaser Abu-Mostafa's "Learning from data" [^yaser] start with similar motivations. 

[^lrn-data]: Shai-Ben David - [Understanding Machine Learning, 2014](https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/understanding-machine-learning-theory-algorithms.pdf). Read chapter 1 and 2 for the intuition. The following ones are difficult, mathematical, but highly rewarding if you want to understand the theoretical foundations of ML. 

[^yaser]: [Learning from data](https://work.caltech.edu/telecourse) is still a great foundational course a decade later. The teaching in the recorded lectures is exceptional

- Implicit learning, intuition, and bias. Bait shyness and pigeon superstition
- The double edged sword of our intelligence. Bounded rationality
- Calling bullshit in the age of Big Data. Small data problems in Big Data
- Intelligence, Rationality, Wisdom, and Foolishness
- The learning problem and empirical risk minimization
- The surprising consequences of Bias-Variance tradeoff

::: {.callout-note}
## Case-Study: ML workflow Demonstration

We can pick a (seemingly) simpler use-case like housing prices prediction, credit default risk assessment, churn prediction, demand forecasting, or recommender systems -- and show how training and prediction look like in code.

I will show that there is much more nuance behind the scenes than what kaggle datasets show, and that often the problem framing makes ML look deceptively simple.

:::



## 12 Steps of Machine Learning

By now, I introduced the bare minimum of motivation, formalism, and practices of Machine Learning for you to get by. However, we need a structured approach to tackle real-world problems with ML models. The methodology I like most is articulated by Cassie Kozyrkov, (ex) Chief Decision Scientist at Google. [^cassie]

- Present the 12 steps with representative examples of classification and regression
- Is the ML project feasible? If yes, is it a good idea?
- Split your damn data. Cross-Validation and hyperparameters. Pitfalls
- Similarities with CRISP-DM, tuckey's EDA, and tidy modeling

::: {.callout-note}
## Case-Study: Mercari pricing challenge

I like this Kaggle challenge and dataset, because of how realistic and open-ended it is. You can keep it simple, with out-of-the-box models, or build some highly customized ML pipelines. 

It also has data which requires a combination of different approaches to feature engineering. It is messy enough that we have to justify how we deal with those missingness patterns and weird data points. Those modeling decisions will have an impact on model performance.

:::

[^cassie]: Cassie Kozyrkov - Making friends with machine learning, [full course](https://www.youtube.com/watch?v=1vkb7BCMQd0). It is 6 hours which will serve you during the entire carreer


##  Price optimization under limited capacity 

In contrast with the newsvendor problem (where prices were fixed), it's time we focus on pricing decisions. The limited capacity of airplane seats, concert tickets, hotel rooms, on the one hand simplifies the problem formulation, but introduces many complexities in practice.

This seemingly simple problem motivates why the young field of revenue management was created. When forecasting the demand, we need to think about how to model it well [^modeling] and take into account most relevant factors influencing it. This is where we have to be careful, or at least aware of what economic theory has to say about demand elasticity, competition, and price discrimination.

On the optimization side, we will keep things simple, as in the newsvendor problem. We will not go into the complexities of dynamic programming.


::: {.callout-note}
## Case-Study: Concerts, Events, and Airlines

We can use the Kaggle simulator for dynamic pricing in the airline industry, get creative with the Mercari Challenge or other open datasets. There isn't a firm which will make such kind of data public, so we need to get creative in how we simulate, estimate, or collect the data from what is available.

Adam Fleischhacker has an excellent [tutorial](https://www.youtube.com/watch?v=RScjq1mkDc0) (Chapter 24: Compelling Decisions and Actions Under Uncertainty) which is a good starting point.

:::

[^modeling]: This is where what we learn in [Module 3](../references.qmd): Applied Bayesian Statistics, especially the hierarchical models help a lot.



## 12 Steps of Statistics. A/B Testing Scheme 

I assume you have been working on Module 2 (Fundamentals of Statistics and Probability) in parallel, so that we can get to a point where we discuss the practical and methodological aspects of A/B testing and randomized experiments.

In this lecture I bridge the gap between the theory/fundamentals and practice. We will see how an end-to-end process of experiment design looks like. In the end, you will learn how to make justified choices in how you set-up and run an experiment.


::: {.callout-note}
## Case-Study: Conversion Rate Optimization

Marketing is one area of online businesses which heavily relies on randomized experiments and A/B tests. Firms try to make the most out of their **advertisement spending** (customer acquisition), by testing **changes in user experience**, promotion, merchandising, to convince a larger proportion of them to buy the product or subscribe (conversion rate).

Read this [end-to-end example](https://towardsdatascience.com/simple-and-complet-guide-to-a-b-testing-c34154d0ce5a), which takes a lot of attention and care into verifying potential pitfalls. If you need other perspectives about what can go wrong, you can refer to: [HBR article](https://hbr.org/2020/03/avoid-the-pitfalls-of-a-b-testing), [8 pitfalls and solutions](https://towardsdatascience.com/online-controlled-experiment-8-common-pitfalls-and-solutions-ea4488e5a82e), [A/A tests](https://towardsdatascience.com/an-a-b-test-loses-its-luster-if-a-a-tests-fail-2dd11fa6d241), and [user interference](https://towardsdatascience.com/how-user-interference-may-mess-up-your-a-b-tests-f29abfcfccf8)

:::

- Before jumping into the hypothesis testing, we should carefully ask whether we need an experiment at all. [^should-exp] Maybe we want to explore or predict?
- [Default action](https://towardsdatascience.com/the-most-important-idea-in-statistics-8c18d514ad1c) is one of the most important ideas in statistics.
- What is a statistical hypothesis anyways? How does it relate to the original question?
    - Make sure you define the minimal effect size of interest/relevance
    - Type 3 errors: be careful what is the question you really ask of your test
- Watch the [12 steps to statistics](https://youtu.be/R4ckbZCgmxQ?si=pkxQD3lG3CIo4NKf) by Cassie Kozyrkov for a methodology of how to perform experiments in business settings. For a more traditional exposition, check out Poldrack's [Chapter 9](https://statsthinking21.github.io/statsthinking21-core-site/hypothesis-testing.html).
- One of the most difficult aspects in practice is metric design, since we deal with tradeoffs so often. An useful way to think about properties of good metrics is described in [this paper, STEDII](https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/articles/stedii-properties-of-a-good-metric/). Also see [this example](https://towardsdatascience.com/a-guide-for-selecting-an-appropriate-metric-for-your-a-b-test-9068cccb7fb) discussing sensitivity, stability, and directedness.

[^should-exp]: Read Cassie Kozyrkov's article to recognize when ["not to waste your time with statistics"](https://towardsdatascience.com/whats-the-point-of-statistics-8163635da56c). You can also watch [this video](https://www.coursera.org/learn/improving-statistical-questions/lecture/uHfmn/lecture-1-2-do-you-really-want-to-test-a-hypothesis). You can also see her [full, short lecture](https://www.youtube.com/playlist?list=PLRKtJ4IpxJpBxX2S9wXJUhB1_ha3ADFpF) for Google employees. 


## Churn and Lifetime Value. Open datasets

Customer retention and repurchase is what makes or breaks businesses, especially in the past few years, with so many subscription and SAAS business models. Therefore, this topic deserves a full lecture -- to cover the contractual and PAYG/non-contractual settings.

I show that predicting churn and remaining customer lifetime value is not just a simple classification / regression problem. First, we need some tools from survival analysis and second -- what we really want to know is who can be convinced to remain by an intervention, like promotions or loyalty programs. [^convince]

::: {.callout-note}
## Case-Study: BTYD models (Buy till you die)

There is a body of work spanning two decades by Bruce Hardie and Peter Fader, who developed statistical models that estimate the remaining LTV (Lifetime Value) of customers, which depends on their survival/activity and repurchase patterns.

We will implement a model for contractual and non-contractual settings on the limited data available on the web. Luckily, that would be sufficient to apply them for your own use-cases.
:::


Last, but not least, I present an overview of curated open datasets from various sources, organized by industry -- which should serve as an inspiration for future practice and your project. There is a shortlist of the ones I found most intriguing and representative, then a long tail of alternatives and fun stuff.

In previous courses you probably did a lot of exploratory data analysis. It is a skill which demands lots of practice and experience in order to do it well (finding inspiration and interesting patterns in data). Having a methodology for EDA helps, however, in practice we have to work with databases.

::: {.callout-note}
## Case-Study: DuckDB and e-commerce database

I use a relational dataset from a real e-commerce which was made public in Kaggle, in order to showcase how to interact with databases and highlight the importance of knowing SQL. 

We use a recent innovation in databases, duckDB, which allows us to have an analytic, in-process database, with almost zero setup or dependencies. Once the e-commerce data is loaded and modeled inside the DB, we can start cleaning it, putting it all together, and extracting insights from it. This particular dataset is very rich in information and lends itself well to open-ended investigations. 

:::


[^convince]: This is a good opportunity to introduce the idea of Uplift and Calibration of classification scores returned by a ML model.